version: "3.8"
services:
  droplet-oauth:
    build: .
    ports:
      - 127.0.0.1:8000:8000
    restart: unless-stopped
    environment:
      - CLIENT_ID
      - CLIENT_SECRET
      - REDIRECT_URL
      - SESSION_KEY
